# Importing all the libraries

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
autos = pd.read_csv("autos.csv", encoding = "Windows-1252")

In [4]:
autos

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,"$7,900",test,bus,2006,automatik,150,voyager,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,2016-04-06 09:45:21
6,2016-03-20 17:55:21,VW_Golf_III_GT_Special_Electronic_Green_Metall...,privat,Angebot,$300,test,limousine,1995,manuell,90,golf,"150,000km",8,benzin,volkswagen,NaN,2016-03-20 00:00:00,0,31535,2016-03-23 02:48:59
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,"$1,990",control,limousine,1998,manuell,90,golf,"150,000km",12,diesel,volkswagen,nein,2016-03-16 00:00:00,0,53474,2016-04-07 03:17:32
8,2016-03-22 16:51:34,Seat_Arosa,privat,Angebot,$250,test,NaN,2000,manuell,0,arosa,"150,000km",10,NaN,seat,nein,2016-03-22 00:00:00,0,7426,2016-03-26 18:18:10
9,2016-03-16 13:47:02,Renault_Megane_Scenic_1.6e_RT_Klimaanlage,privat,Angebot,$590,control,bus,1997,manuell,90,megane,"150,000km",7,benzin,renault,nein,2016-03-16 00:00:00,0,15749,2016-04-06 10:46:35
10,2016-03-15 01:41:36,VW_Golf_Tuning_in_siber/grau,privat,Angebot,$999,test,NaN,2017,manuell,90,NaN,"150,000km",4,benzin,volkswagen,nein,2016-03-14 00:00:00,0,86157,2016-04-07 03:16:21
11,2016-03-16 18:45:34,Mercedes_A140_Motorschaden,privat,Angebot,$350,control,NaN,2000,NaN,0,NaN,"150,000km",0,benzin,mercedes_benz,NaN,2016-03-16 00:00:00,0,17498,2016-03-16 18:45:34
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,"$5,299",control,kleinwagen,2010,automatik,71,fortwo,"50,000km",9,benzin,smart,nein,2016-03-31 00:00:00,0,34590,2016-04-06 14:17:52
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,"$1,350",control,limousine,1999,manuell,101,a3,"150,000km",11,benzin,audi,nein,2016-03-23 00:00:00,0,12043,2016-04-01 14:17:13
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,"$3,999",test,kleinwagen,2007,manuell,75,clio,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,2016-04-01 15:46:47
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,"$18,900",test,coupe,1982,automatik,203,NaN,"80,000km",6,benzin,sonstige_autos,nein,2016-04-01 00:00:00,0,61276,2016-04-02 21:10:48
16,2016-03-16 14:59:02,Opel_Vectra_B_Kombi,privat,Angebot,$350,test,kombi,1999,manuell,101,vectra,"150,000km",5,benzin,opel,nein,2016-03-16 00:00:00,0,57299,2016-03-18 05:29:37
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,"$5,500",test,coupe,1990,manuell,205,scirocco,"150,000km",6,benzin,volkswagen,nein,2016-03-29 00:00:00,0,74821,2016-04-05 20:46:26
18,2016-03-26 19:57:44,Verkaufen_mein_bmw_e36_320_i_touring,privat,Angebot,$300,control,bus,1995,manuell,150,3er,"150,000km",0,benzin,bmw,NaN,2016-03-26 00:00:00,0,54329,2016-04-02 12:16:41
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,"$4,150",control,suv,2004,manuell,124,andere,"150,000km",2,lpg,mazda,nein,2016-03-17 00:00:00,0,40878,2016-03-17 14:45:58
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,"$3,500",test,kombi,2003,manuell,131,a4,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,2016-03-07 05:46:46
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,"$41,500",test,cabrio,2004,manuell,320,911,"150,000km",4,benzin,porsche,nein,2016-03-06 00:00:00,0,65428,2016-04-05 23:46:19
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,"$25,450",control,cabrio,2015,manuell,184,cooper,"10,000km",1,benzin,mini,nein,2016-03-28 00:00:00,0,44789,2016-04-01 06:45:30
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,"$7,999",control,bus,2010,manuell,120,NaN,"150,000km",2,diesel,peugeot,nein,2016-03-10 00:00:00,0,30900,2016-03-17 08:45:17
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,"$48,500",control,limousine,2014,automatik,306,5er,"30,000km",12,benzin,bmw,nein,2016-04-03 00:00:00,0,22547,2016-04-07 13:16:50
25,2016-03-21 21:56:18,Ford_escort_kombi_an_bastler_mit_ghia_ausstattung,privat,Angebot,$90,control,kombi,1996,manuell,116,NaN,"150,000km",4,benzin,ford,ja,2016-03-21 00:00:00,0,27574,2016-04-01 05:16:49
26,2016-04-03 22:46:28,Volkswagen_Polo_Fox,privat,Angebot,$777,control,kleinwagen,1992,manuell,54,polo,"125,000km",2,benzin,volkswagen,nein,2016-04-03 00:00:00,0,38110,2016-04-05 23:46:48
27,2016-03-27 18:45:01,Hat_einer_Ahnung_mit_Ford_Galaxy_HILFE,privat,Angebot,$0,control,NaN,2005,NaN,0,NaN,"150,000km",0,NaN,ford,NaN,2016-03-27 00:00:00,0,66701,2016-03-27 18:45:01
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,"$5,250",control,kleinwagen,2007,manuell,110,cooper,"150,000km",7,diesel,mini,ja,2016-03-19 00:00:00,0,15745,2016-04-07 14:58:48
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,"$4,999",test,kombi,2004,automatik,204,e_klasse,"150,000km",10,diesel,mercedes_benz,nein,2016-04-02 00:00:00,0,47638,2016-04-02 12:45:44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,"$15,800",control,bus,2010,automatik,136,c4,"60,000km",4,diesel,citroen,nein,2016-03-21 00:00:00,0,14947,2016-04-07 04:17:34
49971,2016-03-29 14:54:12,W.Lupo_1.0,privat,Angebot,$950,test,kleinwagen,2001,manuell,50,lupo,"150,000km",4,benzin,volkswagen,nein,2016-03-29 00:00:00,0,65197,2016-03-29 20:41:51
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,"$3,300",control,bus,2004,automatik,150,vito,"150,000km",10,diesel,mercedes_benz,ja,2016-03-26 00:00:00,0,65326,2016-03-28 11:28:18
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,"$6,000",control,cabrio,2004,manuell,163,slk,"150,000km",11,benzin,mercedes_benz,nein,2016-03-27 00:00:00,0,53567,2016-03-27 08:25:24
49974,2016-03-20 10:52:31,Golf_1_Cabrio_Tuev_Neu_viele_Extras_alles_eing...,privat,Angebot,$0,control,cabrio,1983,manuell,70,golf,"150,000km",2,benzin,volkswagen,nein,2016-03-20 00:00:00,0,8209,2016-03-27 19:48:16
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,"$9,700",control,kleinwagen,2012,automatik,88,jazz,"100,000km",11,hybrid,honda,nein,2016-03-27 00:00:00,0,84385,2016-04-05 19:45:34
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,"$5,900",test,kombi,1992,automatik,150,80,"150,000km",12,benzin,audi,nein,2016-03-19 00:00:00,0,36100,2016-04-07 06:16:44
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,"$5,500",control,limousine,2003,manuell,116,c_klasse,"150,000km",2,diesel,mercedes_benz,nein,2016-03-31 00:00:00,0,33739,2016-04-06 12:16:11
49978,2016-04-04 10:37:14,Mercedes_Benz_E_200_Classic,privat,Angebot,$900,control,limousine,1996,automatik,136,e_klasse,"150,000km",9,benzin,mercedes_benz,ja,2016-04-04 00:00:00,0,24405,2016-04-06 12:44:20
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,"$11,000",test,kleinwagen,2011,manuell,90,polo,"70,000km",11,diesel,volkswagen,nein,2016-03-20 00:00:00,0,48455,2016-04-07 01:45:12
49980,2016-03-12 10:55:54,Ford_Escort_Turnier_16V,privat,Angebot,$400,control,kombi,1995,manuell,105,escort,"125,000km",3,benzin,ford,NaN,2016-03-12 00:00:00,0,56218,2016-04-06 17:16:49
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,"$2,000",control,kombi,1998,manuell,115,astra,"150,000km",12,benzin,opel,nein,2016-03-15 00:00:00,0,86859,2016-04-05 17:21:46
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,"$1,950",control,kleinwagen,2004,manuell,0,fabia,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,2016-03-29 18:51:08
49983,2016-03-06 12:43:04,Ford_focus_99,privat,Angebot,$600,test,kleinwagen,1999,manuell,101,focus,"150,000km",4,benzin,ford,NaN,2016-03-06 00:00:00,0,52477,2016-03-09 06:16:08
49984,2016-03-31 22:48:48,Student_sucht_ein__Anfaengerauto___ab_2000_BJ_...,privat,Angebot,$0,test,NaN,2000,NaN,0,NaN,"150,000km",0,NaN,sonstige_autos,NaN,2016-03-31 00:00:00,0,12103,2016-04-02 19:44:53
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,"$1,000",control,NaN,1995,automatik,0,NaN,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,2016-04-06 15:17:52
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,"$15,900",control,limousine,2010,automatik,218,300c,"125,000km",11,diesel,chrysler,nein,2016-04-04 00:00:00,0,73527,2016-04-06 23:16:00
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,"$21,990",control,limousine,2013,manuell,150,a3,"50,000km",11,diesel,audi,nein,2016-03-22 00:00:00,0,94362,2016-03-26 22:46:06
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,"$9,550",control,coupe,2001,manuell,231,3er,"150,000km",10,benzin,bmw,nein,2016-03-28 00:00:00,0,83646,2016-04-07 02:17:40
49989,2016-03-11 19:50:37,VW_Polo_zum_Ausschlachten_oder_Wiederaufbau,privat,Angebot,$150,test,kleinwagen,1997,manuell,0,polo,"150,000km",5,benzin,volkswagen,ja,2016-03-11 00:00:00,0,21244,2016-03-12 10:17:55
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,"$17,500",test,limousine,2012,manuell,156,a_klasse,"30,000km",12,benzin,mercedes_benz,nein,2016-03-21 00:00:00,0,58239,2016-04-06 22:46:57
49991,2016-03-06 15:25:19,Kleinwagen,privat,Angebot,$500,control,NaN,2016,manuell,0,twingo,"150,000km",0,benzin,renault,NaN,2016-03-06 00:00:00,0,61350,2016-03-06 18:24:19
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,"$4,800",control,kleinwagen,2009,manuell,120,andere,"125,000km",9,lpg,fiat,nein,2016-03-10 00:00:00,0,68642,2016-03-13 01:44:51
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,"$1,650",control,kleinwagen,1997,manuell,0,NaN,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,2016-04-06 19:46:53
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,"$5,000",control,kombi,2001,automatik,299,a6,"150,000km",1,benzin,audi,nein,2016-03-22 00:00:00,0,46537,2016-04-06 08:16:39
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [5]:
autos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
dateCrawled            50000 non-null object
name                   50000 non-null object
seller                 50000 non-null object
offerType              50000 non-null object
price                  50000 non-null object
abtest                 50000 non-null object
vehicleType            44905 non-null object
yearOfRegistration     50000 non-null int64
gearbox                47320 non-null object
powerPS                50000 non-null int64
model                  47242 non-null object
odometer               50000 non-null object
monthOfRegistration    50000 non-null int64
fuelType               45518 non-null object
brand                  50000 non-null object
notRepairedDamage      40171 non-null object
dateCreated            50000 non-null object
nrOfPictures           50000 non-null int64
postalCode             50000 non-null int64
lastSeen               50000 non-null object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB

In [6]:
autos.head()

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

# Starting data cleaning from the column row

In [7]:
autos.columns

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

In [8]:
autos.rename(columns={'yearOfRegistration': 'registration_year',
'monthOfRegistration' : 'registration_month',
'notRepairedDamage' : 'unrepaired_damage',
'dateCreated' : 'ad_created',
'dateCrawled':'date_crawled',
'offerType':'offer_type',
'vehicleType': 'vehicle_type',
'powerPS': 'power_ps',
'fuelType': 'fuel_type',
'nrOfPictures':'pictures_quantity',
'postalCode':'postal_code',
'lastSeen':'last_seen'}, inplace = True)

In [9]:
autos.head()

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,pictures_quantity,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

#### Columns names are cleaned according to the standards. Converted from the camel case to the snake case

In [10]:
autos.describe(include= 'all')

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,pictures_quantity,postal_code,last_seen
count,50000,50000,50000,50000,50000,50000,44905,50000.000000,47320,50000.000000,47242,50000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,48213,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,2016-03-11 22:38:16,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.073280,NaN,116.355920,NaN,NaN,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.712813,NaN,209.216627,NaN,NaN,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,70.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.000000,NaN,105.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN,150.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.000000,NaN,17700.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

In [11]:
autos['price'] = autos['price'].str.replace('$','').str.replace(',','').astype(int)

In [12]:
autos['price'].value_counts()

0         1421
500        781
1500       734
2500       643
1000       639
1200       639
600        531
800        498
3500       498
2000       460
999        434
750        433
900        420
650        419
850        410
700        395
4500       394
300        384
2200       382
950        379
1100       376
1300       371
3000       365
550        356
1800       355
5500       340
1250       335
350        335
1600       327
1999       322
          ...
46200        1
29600        1
13480        1
21700        1
7373         1
3279         1
4286         1
188          1
17830        1
9130         1
910          1
238          1
2671         1
69900        1
151990       1
2479         1
4510         1
86500        1
47499        1
16998        1
27299        1
41850        1
4780         1
686          1
6495         1
20790        1
8970         1
846          1
2895         1
33980        1
Name: price, Length: 2357, dtype: int64

In [13]:
autos['odometer_km'] = autos['odometer'].str.replace('km','').str.replace(',','').astype(int)

In [14]:
autos['odometer_km'].describe()

count     50000.000000
mean     125732.700000
std       40042.211706
min        5000.000000
25%      125000.000000
50%      150000.000000
75%      150000.000000
max      150000.000000
Name: odometer_km, dtype: float64

In [15]:
autos['seller'].value_counts()

privat        49999
gewerblich        1
Name: seller, dtype: int64

In [16]:
autos['offer_type'].value_counts()

Angebot    49999
Gesuch         1
Name: offer_type, dtype: int64

In [17]:
autos['price'].unique()

array([ 5000,  8500,  8990, ...,   385, 22200, 16995])

In [18]:
autos['price'].describe()

count    5.000000e+04
mean     9.840044e+03
std      4.811044e+05
min      0.000000e+00
25%      1.100000e+03
50%      2.950000e+03
75%      7.200000e+03
max      1.000000e+08
Name: price, dtype: float64

In [19]:
autos['price'].value_counts().sort_index()

0           1421
1            156
2              3
3              1
5              2
8              1
9              1
10             7
11             2
12             3
13             2
14             1
15             2
17             3
18             1
20             4
25             5
29             1
30             7
35             1
40             6
45             4
47             1
49             4
50            49
55             2
59             1
60             9
65             5
66             1
            ...
151990         1
155000         1
163500         1
163991         1
169000         1
169999         1
175000         1
180000         1
190000         1
194000         1
197000         1
198000         1
220000         1
250000         1
259000         1
265000         1
295000         1
299000         1
345000         1
350000         1
999990         1
999999         2
1234566        1
1300000        1
3890000        1
10000000       1
11111111       2
12345678       3
27322222       1
99999999       1
Name: price, Length: 2357, dtype: int64

In [20]:
autos = autos[autos['price'].between(1000, 3000000)]

In [21]:
autos['price'].value_counts().sort_index()

1000       639
1039         1
1040         1
1049         6
1050        95
1059         1
1070         1
1080         6
1090         4
1095         3
1098         1
1099        44
1100       376
1111        39
1112         1
1119         1
1120         2
1149        10
1150       226
1169         1
1170         1
1180         4
1189         1
1190        37
1195         1
1199       126
1200       639
1201         2
1209         1
1212         2
          ...
129000       1
130000       1
135000       1
137999       1
139997       1
145000       1
151990       1
155000       1
163500       1
163991       1
169000       1
169999       1
175000       1
180000       1
190000       1
194000       1
197000       1
198000       1
220000       1
250000       1
259000       1
265000       1
295000       1
299000       1
345000       1
350000       1
999990       1
999999       2
1234566      1
1300000      1
Name: price, Length: 2093, dtype: int64

In [22]:
autos['odometer_km'].value_counts().sort_index()

5000        507
10000       228
20000       692
30000       748
40000       795
50000       987
60000      1099
70000      1154
80000      1334
90000      1569
100000     1860
125000     4341
150000    23317
Name: odometer_km, dtype: int64

#### I have cleaned price column and removed some outlying data

In [24]:
autos['price'].describe()

count    3.863100e+04
mean     7.397704e+03
std      1.590025e+04
min      1.000000e+03
25%      2.200000e+03
50%      4.350000e+03
75%      8.950000e+03
max      1.300000e+06
Name: price, dtype: float64

In [25]:
autos[['date_crawled','ad_created','last_seen']][0:5]

          date_crawled           ad_created            last_seen
0  2016-03-26 17:47:46  2016-03-26 00:00:00  2016-04-06 06:45:54
1  2016-04-04 13:38:56  2016-04-04 00:00:00  2016-04-06 14:45:08
2  2016-03-26 18:57:24  2016-03-26 00:00:00  2016-04-06 20:15:37
3  2016-03-12 16:58:10  2016-03-12 00:00:00  2016-03-15 03:16:28
4  2016-04-01 14:38:50  2016-04-01 00:00:00  2016-04-01 14:38:50

In [26]:
print(autos['date_crawled'].str[:10])

0        2016-03-26
1        2016-04-04
2        2016-03-26
3        2016-03-12
4        2016-04-01
5        2016-03-21
7        2016-03-16
12       2016-03-31
13       2016-03-23
14       2016-03-23
15       2016-04-01
17       2016-03-29
19       2016-03-17
20       2016-03-05
21       2016-03-06
22       2016-03-28
23       2016-03-10
24       2016-04-03
28       2016-03-19
29       2016-04-02
31       2016-03-14
33       2016-03-15
34       2016-04-05
35       2016-03-29
36       2016-03-16
37       2016-03-23
38       2016-03-21
39       2016-03-11
40       2016-03-07
41       2016-03-10
            ...
49962    2016-03-14
49963    2016-03-26
49964    2016-03-10
49965    2016-03-11
49966    2016-04-02
49967    2016-03-12
49968    2016-04-01
49969    2016-03-17
49970    2016-03-21
49972    2016-03-26
49973    2016-03-27
49975    2016-03-27
49976    2016-03-19
49977    2016-03-31
49979    2016-03-20
49981    2016-03-15
49982    2016-03-29
49985    2016-04-02
49986    2016-04-04
49987    2016-03-22
49988    2016-03-28
49990    2016-03-21
49992    2016-03-10
49993    2016-03-15
49994    2016-03-22
49995    2016-03-27
49996    2016-03-28
49997    2016-04-02
49998    2016-03-08
49999    2016-03-14
Name: date_crawled, Length: 38631, dtype: object

In [27]:
autos['date_crawled'].str[:10].value_counts(dropna=False).sort_index()

2016-03-05     987
2016-03-06     536
2016-03-07    1357
2016-03-08    1260
2016-03-09    1254
2016-03-10    1287
2016-03-11    1267
2016-03-12    1444
2016-03-13     618
2016-03-14    1415
2016-03-15    1299
2016-03-16    1123
2016-03-17    1178
2016-03-18     496
2016-03-19    1357
2016-03-20    1474
2016-03-21    1441
2016-03-22    1257
2016-03-23    1244
2016-03-24    1121
2016-03-25    1179
2016-03-26    1279
2016-03-27    1213
2016-03-28    1366
2016-03-29    1313
2016-03-30    1277
2016-03-31    1213
2016-04-01    1337
2016-04-02    1402
2016-04-03    1512
2016-04-04    1425
2016-04-05     516
2016-04-06     126
2016-04-07      58
Name: date_crawled, dtype: int64

In [28]:
autos['ad_created'].str[:10].value_counts(dropna=False).sort_index()

2015-06-11       1
2015-08-10       1
2015-09-09       1
2015-11-10       1
2015-12-30       1
2016-01-03       1
2016-01-07       1
2016-01-10       2
2016-01-13       1
2016-01-14       1
2016-01-16       1
2016-01-22       1
2016-01-27       3
2016-01-29       1
2016-02-01       1
2016-02-02       2
2016-02-05       2
2016-02-07       1
2016-02-09       1
2016-02-11       1
2016-02-12       2
2016-02-14       2
2016-02-16       1
2016-02-17       1
2016-02-18       2
2016-02-19       3
2016-02-20       1
2016-02-21       2
2016-02-22       1
2016-02-23       4
              ...
2016-03-09    1261
2016-03-10    1274
2016-03-11    1277
2016-03-12    1434
2016-03-13     682
2016-03-14    1351
2016-03-15    1292
2016-03-16    1145
2016-03-17    1166
2016-03-18     513
2016-03-19    1316
2016-03-20    1478
2016-03-21    1452
2016-03-22    1249
2016-03-23    1234
2016-03-24    1121
2016-03-25    1185
2016-03-26    1283
2016-03-27    1208
2016-03-28    1367
2016-03-29    1313
2016-03-30    1271
2016-03-31    1219
2016-04-01    1331
2016-04-02    1389
2016-04-03    1524
2016-04-04    1441
2016-04-05     463
2016-04-06     130
2016-04-07      51
Name: ad_created, Length: 74, dtype: int64

In [29]:
autos['last_seen'].str[:10].value_counts(dropna=False).sort_index()

2016-03-05      42
2016-03-06     138
2016-03-07     176
2016-03-08     241
2016-03-09     344
2016-03-10     379
2016-03-11     453
2016-03-12     857
2016-03-13     324
2016-03-14     463
2016-03-15     579
2016-03-16     597
2016-03-17    1019
2016-03-18     285
2016-03-19     564
2016-03-20     765
2016-03-21     760
2016-03-22     803
2016-03-23     692
2016-03-24     716
2016-03-25     686
2016-03-26     621
2016-03-27     544
2016-03-28     751
2016-03-29     803
2016-03-30     906
2016-03-31     878
2016-04-01     896
2016-04-02     963
2016-04-03     944
2016-04-04     903
2016-04-05    5066
2016-04-06    9066
2016-04-07    5407
Name: last_seen, dtype: int64

In [30]:
autos['registration_year'].describe()

count    38631.000000
mean      2005.678186
std         86.679719
min       1000.000000
25%       2001.000000
50%       2005.000000
75%       2009.000000
max       9999.000000
Name: registration_year, dtype: float64

In [31]:
autos['registration_year'].value_counts().sort_index()

1000       1
1001       1
1927       1
1929       1
1931       1
1934       2
1937       4
1938       1
1939       1
1941       2
1943       1
1948       1
1950       1
1951       2
1952       1
1953       1
1954       2
1955       2
1956       4
1957       2
1958       3
1959       6
1960      17
1961       6
1962       4
1963       8
1964       9
1965      17
1966      21
1967      25
        ...
1999    1725
2000    2001
2001    2065
2002    2135
2003    2477
2004    2608
2005    2785
2006    2651
2007    2259
2008    2204
2009    2077
2010    1584
2011    1617
2012    1306
2013     795
2014     649
2015     361
2016     651
2017    1008
2018     398
2019       1
2800       1
4100       1
4500       1
5000       2
5911       1
6200       1
8888       1
9000       1
9999       2
Name: registration_year, Length: 91, dtype: int64

In [32]:
autos = autos[autos['registration_year'].between(1920, 2016)]
#cleaning some odd values in the registration year column
#lowest value will be 1927(its safe to remove two odd values: 100 and 1001)
#highest value is 2016 because a car can't be first registered after the listing was seen

In [33]:
autos['registration_year'].describe()

count    37211.000000
mean      2003.967563
std          7.021114
min       1927.000000
25%       2001.000000
50%       2005.000000
75%       2008.000000
max       2016.000000
Name: registration_year, dtype: float64

In [34]:
autos['registration_year'].value_counts(normalize=True)

2005    0.074843
2006    0.071242
2004    0.070087
2003    0.066566
2007    0.060708
2008    0.059230
2002    0.057376
2009    0.055817
2001    0.055494
2000    0.053774
1999    0.046357
2011    0.043455
2010    0.042568
2012    0.035097
1998    0.034479
2013    0.021365
1997    0.021150
2016    0.017495
2014    0.017441
1996    0.014566
1995    0.011905
2015    0.009701
1994    0.007283
1992    0.005885
1993    0.005858
1991    0.005563
1990    0.005079
1989    0.003305
1988    0.002849
1985    0.002150
          ...
1976    0.000564
1977    0.000537
1975    0.000484
1969    0.000484
1965    0.000457
1960    0.000457
1964    0.000242
1963    0.000215
1959    0.000161
1961    0.000161
1956    0.000107
1962    0.000107
1937    0.000107
1958    0.000081
1954    0.000054
1955    0.000054
1941    0.000054
1957    0.000054
1934    0.000054
1951    0.000054
1953    0.000027
1943    0.000027
1927    0.000027
1929    0.000027
1931    0.000027
1950    0.000027
1948    0.000027
1938    0.000027
1939    0.000027
1952    0.000027
Name: registration_year, Length: 77, dtype: float64

In [35]:
autos['brand'].unique()

array(['peugeot', 'bmw', 'volkswagen', 'smart', 'ford', 'chrysler',
       'audi', 'renault', 'sonstige_autos', 'mazda', 'porsche', 'mini',
       'mercedes_benz', 'seat', 'toyota', 'opel', 'dacia', 'jeep', 'saab',
       'volvo', 'nissan', 'jaguar', 'skoda', 'subaru', 'fiat',
       'mitsubishi', 'chevrolet', 'hyundai', 'honda', 'kia', 'citroen',
       'suzuki', 'trabant', 'land_rover', 'alfa_romeo', 'rover',
       'daihatsu', 'daewoo', 'lancia', 'lada'], dtype=object)

In [36]:
autos['brand'].value_counts(normalize=True)
#for aggregation we will choose brands that have over 5% of the total values
#volkswagen      21%
#bmw             12%
#mercedes_benz   11%
#audi            9%
#opel            8%
#ford            5%

volkswagen        0.210825
bmw               0.125366
mercedes_benz     0.111580
audi              0.097579
opel              0.089060
ford              0.058719
renault           0.037274
peugeot           0.027895
fiat              0.021069
skoda             0.019054
seat              0.017280
smart             0.016608
toyota            0.014619
mazda             0.014243
citroen           0.013894
nissan            0.013625
mini              0.010884
hyundai           0.010750
sonstige_autos    0.010481
volvo             0.008976
kia               0.007686
porsche           0.007471
honda             0.007337
mitsubishi        0.006880
chevrolet         0.006611
alfa_romeo        0.006235
suzuki            0.005724
dacia             0.003279
chrysler          0.003171
jeep              0.002768
land_rover        0.002634
jaguar            0.001854
subaru            0.001720
daihatsu          0.001693
saab              0.001371
daewoo            0.000914
trabant           0.000860
rover             0.000726
lancia            0.000672
lada              0.000618
Name: brand, dtype: float64

In [37]:
autos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37211 entries, 0 to 49999
Data columns (total 21 columns):
date_crawled          37211 non-null object
name                  37211 non-null object
seller                37211 non-null object
offer_type            37211 non-null object
price                 37211 non-null int64
abtest                37211 non-null object
vehicle_type          35873 non-null object
registration_year     37211 non-null int64
gearbox               35936 non-null object
power_ps              37211 non-null int64
model                 35775 non-null object
odometer              37211 non-null object
registration_month    37211 non-null int64
fuel_type             35374 non-null object
brand                 37211 non-null object
unrepaired_damage     32027 non-null object
ad_created            37211 non-null object
pictures_quantity     37211 non-null int64
postal_code           37211 non-null int64
last_seen             37211 non-null object
odometer_km           37211 non-null int64
dtypes: int64(7), object(14)
memory usage: 6.2+ MB

In [38]:
top_brands = {}
brands = ['volkswagen', 'bmw', 'mercedes_benz', 'audi', 'opel', 'ford' ]

In [39]:
for b in brands:
    selected_rows = autos[autos['brand'] == b]
    price_mean = selected_rows['price'].mean()
    top_brands[b] = price_mean
print(top_brands)

{'mercedes_benz': 9302.614402697494, 'bmw': 9381.89174705252, 'ford': 5786.703432494279, 'volkswagen': 6898.376545570427, 'opel': 4219.954737477368, 'audi': 10322.269347287249}

#The most popular selling cars on this eBay site are in two pricing tiers:
#High-price tier (Audi, Mercedes-Benz, BMW)
#Mid-price tier (Volkswagen, Ford, Opel)

In [40]:
mileage_km = {}
for b in brands:
    selected_row = autos[autos['brand'] == b]
    mileage_mean = selected_row['odometer_km'].mean()
    mileage_km[b] = mileage_mean
print(mileage_km)

{'mercedes_benz': 130062.6204238921, 'bmw': 132005.359056806, 'ford': 119622.42562929062, 'volkswagen': 125771.82919056724, 'opel': 123952.92697646348, 'audi': 127491.04929771413}

In [41]:
#series constructor
bmp_series = pd.Series(top_brands)
print(bmp_series)

audi             10322.269347
bmw               9381.891747
ford              5786.703432
mercedes_benz     9302.614403
opel              4219.954737
volkswagen        6898.376546
dtype: float64

In [42]:
df = pd.DataFrame(bmp_series, columns=['mean_price'])
df

                 mean_price
audi           10322.269347
bmw             9381.891747
ford            5786.703432
mercedes_benz   9302.614403
opel            4219.954737
volkswagen      6898.376546

In [43]:
bmp_2series = pd.Series(mileage_km)
df['mean_mileage'] = bmp_2series
df

                 mean_price   mean_mileage
audi           10322.269347  127491.049298
bmw             9381.891747  132005.359057
ford            5786.703432  119622.425629
mercedes_benz   9302.614403  130062.620424
opel            4219.954737  123952.926976
volkswagen      6898.376546  125771.829191

#Although the mean mileage for each brand is roughly the same, the average price for the brands varies greatly.

In [44]:
autos['unrepaired_damage'].unique()

array(['nein', nan, 'ja'], dtype=object)

In [48]:
#translating some columns from german to english
unrepaired_damage_dict = {'nein':'no', 'ja':'yes', 'yes':'yes'}
autos['unrepaired_damage'] = autos['unrepaired_damage'].map(unrepaired_damage_dict)
autos['unrepaired_damage']

0         no
1         no
2         no
3         no
4         no
5        NaN
7         no
12        no
13        no
14       NaN
15        no
17        no
19        no
20       NaN
21        no
22        no
23        no
24        no
28       yes
29        no
31        no
33        no
34       NaN
35        no
36        no
37        no
38        no
39        no
40        no
41        no
        ...
49962    yes
49963     no
49964    NaN
49965     no
49966    yes
49967    NaN
49968     no
49969     no
49970     no
49972    yes
49973     no
49975     no
49976     no
49977     no
49979     no
49981     no
49982    NaN
49985    NaN
49986     no
49987     no
49988     no
49990     no
49992     no
49993    NaN
49994     no
49995     no
49996     no
49997     no
49998     no
49999     no
Name: unrepaired_damage, Length: 37211, dtype: object

In [49]:
autos['vehicle_type'].unique()

array(['bus', 'limousine', 'kleinwagen', 'kombi', 'coupe', 'suv',
       'cabrio', nan, 'andere'], dtype=object)

In [50]:
vehicle_type_dict = {'bus':'bus', 'kleinwagen':'compact car', 'kombi':'estate car', 'cabrio': 'cabriolet', 'andere':'other'}
autos['vehicle_type'] = autos['vehicle_type'].map(vehicle_type_dict)
autos['vehicle_type']

0                bus
1                NaN
2                NaN
3        compact car
4         estate car
5                bus
7                NaN
12       compact car
13               NaN
14       compact car
15               NaN
17               NaN
19               NaN
20        estate car
21         cabriolet
22         cabriolet
23               bus
24               NaN
28       compact car
29        estate car
31        estate car
33        estate car
34        estate car
35        estate car
36        estate car
37               bus
38               NaN
39        estate car
40         cabriolet
41        estate car
            ...
49962            NaN
49963            bus
49964     estate car
49965            NaN
49966    compact car
49967     estate car
49968            NaN
49969            NaN
49970            bus
49972            bus
49973      cabriolet
49975    compact car
49976     estate car
49977            NaN
49979    compact car
49981     estate car
49982    compact car
49985            NaN
49986            NaN
49987            NaN
49988            NaN
49990            NaN
49992    compact car
49993    compact car
49994     estate car
49995            NaN
49996      cabriolet
49997      cabriolet
49998     estate car
49999            NaN
Name: vehicle_type, Length: 37211, dtype: object

In [53]:
#Convert the dates to be uniform numeric data
autos['last_seen'] = autos['last_seen'].str[:10].str.split('-').str.join('').astype(int)

AttributeError: Can only use .str accessor with string values, which use np.object_ dtype in pandas

In [55]:
autos['last_seen'].unique()

array([20160406, 20160315, 20160401, 20160407, 20160402, 20160405,
       20160317, 20160307, 20160316, 20160328, 20160312, 20160324,
       20160404, 20160330, 20160320, 20160403, 20160314, 20160326,
       20160310, 20160327, 20160329, 20160311, 20160331, 20160322,
       20160323, 20160325, 20160319, 20160321, 20160313, 20160308,
       20160318, 20160309, 20160305, 20160306])

In [56]:
autos

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,...,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,pictures_quantity,postal_code,last_seen,odometer_km
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,5000,control,bus,2004,manuell,158,...,"150,000km",3,lpg,peugeot,no,2016-03-26 00:00:00,0,79588,20160406,150000
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,8500,control,NaN,1997,automatik,286,...,"150,000km",6,benzin,bmw,no,2016-04-04 00:00:00,0,71034,20160406,150000
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,8990,test,NaN,2009,manuell,102,...,"70,000km",7,benzin,volkswagen,no,2016-03-26 00:00:00,0,35394,20160406,70000
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,4350,control,compact car,2007,automatik,71,...,"70,000km",6,benzin,smart,no,2016-03-12 00:00:00,0,33729,20160315,70000
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,privat,Angebot,1350,test,estate car,2003,manuell,0,...,"150,000km",7,benzin,ford,no,2016-04-01 00:00:00,0,39218,20160401,150000
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,privat,Angebot,7900,test,bus,2006,automatik,150,...,"150,000km",4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,20160406,150000
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,privat,Angebot,1990,control,NaN,1998,manuell,90,...,"150,000km",12,diesel,volkswagen,no,2016-03-16 00:00:00,0,53474,20160407,150000
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,privat,Angebot,5299,control,compact car,2010,automatik,71,...,"50,000km",9,benzin,smart,no,2016-03-31 00:00:00,0,34590,20160406,50000
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,privat,Angebot,1350,control,NaN,1999,manuell,101,...,"150,000km",11,benzin,audi,no,2016-03-23 00:00:00,0,12043,20160401,150000
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,privat,Angebot,3999,test,compact car,2007,manuell,75,...,"150,000km",9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,20160401,150000
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,privat,Angebot,18900,test,NaN,1982,automatik,203,...,"80,000km",6,benzin,sonstige_autos,no,2016-04-01 00:00:00,0,61276,20160402,80000
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,privat,Angebot,5500,test,NaN,1990,manuell,205,...,"150,000km",6,benzin,volkswagen,no,2016-03-29 00:00:00,0,74821,20160405,150000
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,privat,Angebot,4150,control,NaN,2004,manuell,124,...,"150,000km",2,lpg,mazda,no,2016-03-17 00:00:00,0,40878,20160317,150000
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,privat,Angebot,3500,test,estate car,2003,manuell,131,...,"150,000km",5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,20160307,150000
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,privat,Angebot,41500,test,cabriolet,2004,manuell,320,...,"150,000km",4,benzin,porsche,no,2016-03-06 00:00:00,0,65428,20160405,150000
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,privat,Angebot,25450,control,cabriolet,2015,manuell,184,...,"10,000km",1,benzin,mini,no,2016-03-28 00:00:00,0,44789,20160401,10000
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,privat,Angebot,7999,control,bus,2010,manuell,120,...,"150,000km",2,diesel,peugeot,no,2016-03-10 00:00:00,0,30900,20160317,150000
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,privat,Angebot,48500,control,NaN,2014,automatik,306,...,"30,000km",12,benzin,bmw,no,2016-04-03 00:00:00,0,22547,20160407,30000
28,2016-03-19 21:56:19,MINI_Cooper_D,privat,Angebot,5250,control,compact car,2007,manuell,110,...,"150,000km",7,diesel,mini,yes,2016-03-19 00:00:00,0,15745,20160407,150000
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,privat,Angebot,4999,test,estate car,2004,automatik,204,...,"150,000km",10,diesel,mercedes_benz,no,2016-04-02 00:00:00,0,47638,20160402,150000
31,2016-03-14 16:53:09,Noch_gut_erhaltenen_C_320,privat,Angebot,2850,test,estate car,2002,automatik,218,...,"150,000km",7,benzin,mercedes_benz,no,2016-03-14 00:00:00,0,41065,20160316,150000
33,2016-03-15 12:25:26,Audi_A3_2.0_TDI_Sportback_DPF_Kupplung_defekt_...,privat,Angebot,4800,test,estate car,2006,manuell,140,...,"150,000km",8,diesel,audi,no,2016-03-15 00:00:00,0,61169,20160407,150000
34,2016-04-05 07:55:07,Bmw_530d__navi_tuv03/18,privat,Angebot,2600,test,estate car,2000,automatik,193,...,"150,000km",6,diesel,bmw,NaN,2016-04-05 00:00:00,0,95111,20160407,150000
35,2016-03-29 21:52:56,Ford_Mondeo,privat,Angebot,1200,test,estate car,1998,manuell,0,...,"150,000km",12,benzin,ford,no,2016-03-29 00:00:00,0,52428,20160406,150000
36,2016-03-16 23:46:31,Ford_Mondeo_2.0_Turnier_TDCi_DPF_Titanium,privat,Angebot,7500,test,estate car,2007,manuell,131,...,"150,000km",11,diesel,ford,no,2016-03-16 00:00:00,0,34246,20160405,150000
37,2016-03-23 16:47:46,Seat_Altea_XL_2.0_TDI_CR_DPF_Style,privat,Angebot,13800,test,bus,2012,manuell,140,...,"90,000km",2,diesel,seat,no,2016-03-23 00:00:00,0,85113,20160405,90000
38,2016-03-21 15:51:10,Volkswagen_Golf_1.4_Special,privat,Angebot,2850,control,NaN,2002,manuell,75,...,"125,000km",2,benzin,volkswagen,no,2016-03-21 00:00:00,0,63674,20160328,125000
39,2016-03-11 13:58:38,Mercedes_C_180_Kombi__zu_verkaufen,privat,Angebot,1450,test,estate car,1999,automatik,122,...,"150,000km",6,benzin,mercedes_benz,no,2016-03-11 00:00:00,0,12683,20160406,150000
40,2016-03-07 14:50:03,VW_Golf__4_Cabrio_2.0_GTI_16V___Leder_MFA_Alus...,privat,Angebot,3500,control,cabriolet,1999,manuell,150,...,"150,000km",1,benzin,volkswagen,no,2016-03-07 00:00:00,0,6780,20160312,150000
41,2016-03-10 10:46:08,Passat_3b_1.9_TDI_Highline__angemeldet_mit_tuv...,privat,Angebot,3200,test,estate car,2003,manuell,131,...,"150,000km",7,NaN,volkswagen,no,2016-03-10 00:00:00,0,28259,20160406,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49962,2016-03-14 17:57:15,Mitsubishi_Space_Star_1__3_L__Bj_2004_Standhei...,privat,Angebot,2200,test,NaN,2004,manuell,82,...,"150,000km",4,benzin,mitsubishi,yes,2016-03-14 00:00:00,0,45481,20160315,150000
49963,2016-03-26 19:52:59,Mercedes_Benz_B_200_CDI_Special_Edition,privat,Angebot,7600,control,bus,2007,manuell,140,...,"125,000km",5,diesel,mercedes_benz,no,2016-03-26 00:00:00,0,92272,20160328,125000
49964,2016-03-10 16:46:43,Audi_2_7_TDI_AVANT,privat,Angebot,12700,control,estate car,2010,automatik,192,...,"150,000km",5,diesel,audi,NaN,2016-03-10 00:00:00,0,54441,20160407,150000
49965,2016-03-11 10:53:51,Opel_Astra_1.6_Lenkradheizung~Sitzheizung,privat,Angebot,6700,test,NaN,2011,manuell,116,...,"125,000km",3,benzin,opel,no,2016-03-11 00:00:00,0,37627,20160315,125000
49966,2016-04-02 19:49:19,CitroÃ«n_C1_1.0_**Euro4**TÃœV_OKT_2017**Scheiten...,privat,Angebot,1490,control,compact car,2006,manuell,68,...,"150,000km",7,benzin,citroen,yes,2016-04-02 00:00:00,0,26603,20160402,150000
49967,2016-03-12 11:50:17,VW_Passat_2_0_TDI_comfortline,privat,Angebot,4999,test,estate car,2006,manuell,140,...,"150,000km",5,diesel,volkswagen,NaN,2016-03-12 00:00:00,0,70619,20160317,150000
49968,2016-04-01 17:49:15,Mercedes_Benz_190_D_2.5_Automatik,privat,Angebot,2100,test,NaN,1986,automatik,90,...,"150,000km",9,diesel,mercedes_benz,no,2016-04-01 00:00:00,0,40227,20160405,150000
49969,2016-03-17 18:49:02,Nissan_X_Trail_2.2_dCi_4x4_Sport_m.AHZ,privat,Angebot,4500,control,NaN,2005,manuell,136,...,"150,000km",5,diesel,nissan,no,2016-03-17 00:00:00,0,17379,20160325,150000
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,privat,Angebot,15800,control,bus,2010,automatik,136,...,"60,000km",4,diesel,citroen,no,2016-03-21 00:00:00,0,14947,20160407,60000
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,privat,Angebot,3300,control,bus,2004,automatik,150,...,"150,000km",10,diesel,mercedes_benz,yes,2016-03-26 00:00:00,0,65326,20160328,150000
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,privat,Angebot,6000,control,cabriolet,2004,manuell,163,...,"150,000km",11,benzin,mercedes_benz,no,2016-03-27 00:00:00,0,53567,20160327,150000
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,privat,Angebot,9700,control,compact car,2012,automatik,88,...,"100,000km",11,hybrid,honda,no,2016-03-27 00:00:00,0,84385,20160405,100000
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,privat,Angebot,5900,test,estate car,1992,automatik,150,...,"150,000km",12,benzin,audi,no,2016-03-19 00:00:00,0,36100,20160407,150000
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,privat,Angebot,5500,control,NaN,2003,manuell,116,...,"150,000km",2,diesel,mercedes_benz,no,2016-03-31 00:00:00,0,33739,20160406,150000
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,privat,Angebot,11000,test,compact car,2011,manuell,90,...,"70,000km",11,diesel,volkswagen,no,2016-03-20 00:00:00,0,48455,20160407,70000
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,privat,Angebot,2000,control,estate car,1998,manuell,115,...,"150,000km",12,benzin,opel,no,2016-03-15 00:00:00,0,86859,20160405,150000
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,privat,Angebot,1950,control,compact car,2004,manuell,0,...,"90,000km",7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,20160329,90000
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,privat,Angebot,1000,control,NaN,1995,automatik,0,...,"150,000km",0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,20160406,150000
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,privat,Angebot,15900,control,NaN,2010,automatik,218,...,"125,000km",11,diesel,chrysler,no,2016-04-04 00:00:00,0,73527,20160406,125000
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,privat,Angebot,21990,control,NaN,2013,manuell,150,...,"50,000km",11,diesel,audi,no,2016-03-22 00:00:00,0,94362,20160326,50000
49988,2016-03-28 19:49:51,BMW_330_Ci,privat,Angebot,9550,control,NaN,2001,manuell,231,...,"150,000km",10,benzin,bmw,no,2016-03-28 00:00:00,0,83646,20160407,150000
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,privat,Angebot,17500,test,NaN,2012,manuell,156,...,"30,000km",12,benzin,mercedes_benz,no,2016-03-21 00:00:00,0,58239,20160406,30000
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,privat,Angebot,4800,control,compact car,2009,manuell,120,...,"125,000km",9,lpg,fiat,no,2016-03-10 00:00:00,0,68642,20160313,125000
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,privat,Angebot,1650,control,compact car,1997,manuell,0,...,"150,000km",7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,20160406,150000
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,privat,Angebot,5000,control,estate car,2001,automatik,299,...,"150,000km",1,benzin,audi,no,2016-03-22 00:00:00,0,46537,20160406,150000
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,24900,control,NaN,2011,automatik,239,...,"100,000km",1,diesel,audi,no,2016-03-27 00:00:00,0,82131,20160401,100000
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,privat,Angebot,1980,control,cabriolet,1996,manuell,75,...,"150,000km",5,benzin,opel,no,2016-03-28 00:00:00,0,44807,20160402,150000
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,13200,test,cabriolet,2014,automatik,69,...,"5,000km",11,benzin,fiat,no,2016-04-02 00:00:00,0,73430,20160404,5000
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,22900,control,estate car,2013,manuell,150,...,"40,000km",11,diesel,audi,no,2016-03-08 00:00:00,0,35683,20160405,40000
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,1250,control,NaN,1996,manuell,101,...,"150,000km",1,benzin,opel,no,2016-03-13 00:00:00,0,45897,20160406,150000

In [57]:
autos = autos.drop(['seller','offer_type','odometer'],axis = 1)

In [58]:
autos

,date_crawled,name,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,registration_month,fuel_type,brand,unrepaired_damage,ad_created,pictures_quantity,postal_code,last_seen,odometer_km
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,5000,control,bus,2004,manuell,158,andere,3,lpg,peugeot,no,2016-03-26 00:00:00,0,79588,20160406,150000
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,8500,control,NaN,1997,automatik,286,7er,6,benzin,bmw,no,2016-04-04 00:00:00,0,71034,20160406,150000
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,8990,test,NaN,2009,manuell,102,golf,7,benzin,volkswagen,no,2016-03-26 00:00:00,0,35394,20160406,70000
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,4350,control,compact car,2007,automatik,71,fortwo,6,benzin,smart,no,2016-03-12 00:00:00,0,33729,20160315,70000
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÃœV_neu_ist_sehr_gepfleg...,1350,test,estate car,2003,manuell,0,focus,7,benzin,ford,no,2016-04-01 00:00:00,0,39218,20160401,150000
5,2016-03-21 13:47:45,Chrysler_Grand_Voyager_2.8_CRD_Aut.Limited_Sto...,7900,test,bus,2006,automatik,150,voyager,4,diesel,chrysler,NaN,2016-03-21 00:00:00,0,22962,20160406,150000
7,2016-03-16 18:55:19,Golf_IV_1.9_TDI_90PS,1990,control,NaN,1998,manuell,90,golf,12,diesel,volkswagen,no,2016-03-16 00:00:00,0,53474,20160407,150000
12,2016-03-31 19:48:22,Smart_smart_fortwo_coupe_softouch_pure_MHD_Pan...,5299,control,compact car,2010,automatik,71,fortwo,9,benzin,smart,no,2016-03-31 00:00:00,0,34590,20160406,50000
13,2016-03-23 10:48:32,Audi_A3_1.6_tuning,1350,control,NaN,1999,manuell,101,a3,11,benzin,audi,no,2016-03-23 00:00:00,0,12043,20160401,150000
14,2016-03-23 11:50:46,Renault_Clio_3__Dynamique_1.2__16_V;_viele_Ver...,3999,test,compact car,2007,manuell,75,clio,9,benzin,renault,NaN,2016-03-23 00:00:00,0,81737,20160401,150000
15,2016-04-01 12:06:20,Corvette_C3_Coupe_T_Top_Crossfire_Injection,18900,test,NaN,1982,automatik,203,NaN,6,benzin,sonstige_autos,no,2016-04-01 00:00:00,0,61276,20160402,80000
17,2016-03-29 11:46:22,Volkswagen_Scirocco_2_G60,5500,test,NaN,1990,manuell,205,scirocco,6,benzin,volkswagen,no,2016-03-29 00:00:00,0,74821,20160405,150000
19,2016-03-17 13:36:21,mazda_tribute_2.0_mit_gas_und_tuev_neu_2018,4150,control,NaN,2004,manuell,124,andere,2,lpg,mazda,no,2016-03-17 00:00:00,0,40878,20160317,150000
20,2016-03-05 19:57:31,Audi_A4_Avant_1.9_TDI_*6_Gang*AHK*Klimatronik*...,3500,test,estate car,2003,manuell,131,a4,5,diesel,audi,NaN,2016-03-05 00:00:00,0,53913,20160307,150000
21,2016-03-06 19:07:10,Porsche_911_Carrera_4S_Cabrio,41500,test,cabriolet,2004,manuell,320,911,4,benzin,porsche,no,2016-03-06 00:00:00,0,65428,20160405,150000
22,2016-03-28 20:50:54,MINI_Cooper_S_Cabrio,25450,control,cabriolet,2015,manuell,184,cooper,1,benzin,mini,no,2016-03-28 00:00:00,0,44789,20160401,10000
23,2016-03-10 19:55:34,Peugeot_Boxer_2_2_HDi_120_Ps_9_Sitzer_inkl_Klima,7999,control,bus,2010,manuell,120,NaN,2,diesel,peugeot,no,2016-03-10 00:00:00,0,30900,20160317,150000
24,2016-04-03 11:57:02,BMW_535i_xDrive_Sport_Aut.,48500,control,NaN,2014,automatik,306,5er,12,benzin,bmw,no,2016-04-03 00:00:00,0,22547,20160407,30000
28,2016-03-19 21:56:19,MINI_Cooper_D,5250,control,compact car,2007,manuell,110,cooper,7,diesel,mini,yes,2016-03-19 00:00:00,0,15745,20160407,150000
29,2016-04-02 12:45:44,Mercedes_Benz_E_320_T_CDI_Avantgarde_DPF7_Sitz...,4999,test,estate car,2004,automatik,204,e_klasse,10,diesel,mercedes_benz,no,2016-04-02 00:00:00,0,47638,20160402,150000
31,2016-03-14 16:53:09,Noch_gut_erhaltenen_C_320,2850,test,estate car,2002,automatik,218,c_klasse,7,benzin,mercedes_benz,no,2016-03-14 00:00:00,0,41065,20160316,150000
33,2016-03-15 12:25:26,Audi_A3_2.0_TDI_Sportback_DPF_Kupplung_defekt_...,4800,test,estate car,2006,manuell,140,a3,8,diesel,audi,no,2016-03-15 00:00:00,0,61169,20160407,150000
34,2016-04-05 07:55:07,Bmw_530d__navi_tuv03/18,2600,test,estate car,2000,automatik,193,5er,6,diesel,bmw,NaN,2016-04-05 00:00:00,0,95111,20160407,150000
35,2016-03-29 21:52:56,Ford_Mondeo,1200,test,estate car,1998,manuell,0,mondeo,12,benzin,ford,no,2016-03-29 00:00:00,0,52428,20160406,150000
36,2016-03-16 23:46:31,Ford_Mondeo_2.0_Turnier_TDCi_DPF_Titanium,7500,test,estate car,2007,manuell,131,mondeo,11,diesel,ford,no,2016-03-16 00:00:00,0,34246,20160405,150000
37,2016-03-23 16:47:46,Seat_Altea_XL_2.0_TDI_CR_DPF_Style,13800,test,bus,2012,manuell,140,altea,2,diesel,seat,no,2016-03-23 00:00:00,0,85113,20160405,90000
38,2016-03-21 15:51:10,Volkswagen_Golf_1.4_Special,2850,control,NaN,2002,manuell,75,golf,2,benzin,volkswagen,no,2016-03-21 00:00:00,0,63674,20160328,125000
39,2016-03-11 13:58:38,Mercedes_C_180_Kombi__zu_verkaufen,1450,test,estate car,1999,automatik,122,c_klasse,6,benzin,mercedes_benz,no,2016-03-11 00:00:00,0,12683,20160406,150000
40,2016-03-07 14:50:03,VW_Golf__4_Cabrio_2.0_GTI_16V___Leder_MFA_Alus...,3500,control,cabriolet,1999,manuell,150,golf,1,benzin,volkswagen,no,2016-03-07 00:00:00,0,6780,20160312,150000
41,2016-03-10 10:46:08,Passat_3b_1.9_TDI_Highline__angemeldet_mit_tuv...,3200,test,estate car,2003,manuell,131,NaN,7,NaN,volkswagen,no,2016-03-10 00:00:00,0,28259,20160406,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49962,2016-03-14 17:57:15,Mitsubishi_Space_Star_1__3_L__Bj_2004_Standhei...,2200,test,NaN,2004,manuell,82,andere,4,benzin,mitsubishi,yes,2016-03-14 00:00:00,0,45481,20160315,150000
49963,2016-03-26 19:52:59,Mercedes_Benz_B_200_CDI_Special_Edition,7600,control,bus,2007,manuell,140,b_klasse,5,diesel,mercedes_benz,no,2016-03-26 00:00:00,0,92272,20160328,125000
49964,2016-03-10 16:46:43,Audi_2_7_TDI_AVANT,12700,control,estate car,2010,automatik,192,a4,5,diesel,audi,NaN,2016-03-10 00:00:00,0,54441,20160407,150000
49965,2016-03-11 10:53:51,Opel_Astra_1.6_Lenkradheizung~Sitzheizung,6700,test,NaN,2011,manuell,116,astra,3,benzin,opel,no,2016-03-11 00:00:00,0,37627,20160315,125000
49966,2016-04-02 19:49:19,CitroÃ«n_C1_1.0_**Euro4**TÃœV_OKT_2017**Scheiten...,1490,control,compact car,2006,manuell,68,c1,7,benzin,citroen,yes,2016-04-02 00:00:00,0,26603,20160402,150000
49967,2016-03-12 11:50:17,VW_Passat_2_0_TDI_comfortline,4999,test,estate car,2006,manuell,140,passat,5,diesel,volkswagen,NaN,2016-03-12 00:00:00,0,70619,20160317,150000
49968,2016-04-01 17:49:15,Mercedes_Benz_190_D_2.5_Automatik,2100,test,NaN,1986,automatik,90,andere,9,diesel,mercedes_benz,no,2016-04-01 00:00:00,0,40227,20160405,150000
49969,2016-03-17 18:49:02,Nissan_X_Trail_2.2_dCi_4x4_Sport_m.AHZ,4500,control,NaN,2005,manuell,136,x_trail,5,diesel,nissan,no,2016-03-17 00:00:00,0,17379,20160325,150000
49970,2016-03-21 22:47:37,c4_Grand_Picasso_mit_Automatik_Leder_Navi_Temp...,15800,control,bus,2010,automatik,136,c4,4,diesel,citroen,no,2016-03-21 00:00:00,0,14947,20160407,60000
49972,2016-03-26 22:25:23,Mercedes_Benz_Vito_115_CDI_Extralang_Aut.,3300,control,bus,2004,automatik,150,vito,10,diesel,mercedes_benz,yes,2016-03-26 00:00:00,0,65326,20160328,150000
49973,2016-03-27 05:32:39,Mercedes_Benz_SLK_200_Kompressor,6000,control,cabriolet,2004,manuell,163,slk,11,benzin,mercedes_benz,no,2016-03-27 00:00:00,0,53567,20160327,150000
49975,2016-03-27 20:51:39,Honda_Jazz_1.3_DSi_i_VTEC_IMA_CVT_Comfort,9700,control,compact car,2012,automatik,88,jazz,11,hybrid,honda,no,2016-03-27 00:00:00,0,84385,20160405,100000
49976,2016-03-19 18:56:05,Audi_80_Avant_2.6_E__Vollausstattung!!_Einziga...,5900,test,estate car,1992,automatik,150,80,12,benzin,audi,no,2016-03-19 00:00:00,0,36100,20160407,150000
49977,2016-03-31 18:37:18,Mercedes_Benz_C200_Cdi_W203,5500,control,NaN,2003,manuell,116,c_klasse,2,diesel,mercedes_benz,no,2016-03-31 00:00:00,0,33739,20160406,150000
49979,2016-03-20 18:38:40,Volkswagen_Polo_1.6_TDI_Style,11000,test,compact car,2011,manuell,90,polo,11,diesel,volkswagen,no,2016-03-20 00:00:00,0,48455,20160407,70000
49981,2016-03-15 09:38:21,Opel_Astra_Kombi_mit_Anhaengerkupplung,2000,control,estate car,1998,manuell,115,astra,12,benzin,opel,no,2016-03-15 00:00:00,0,86859,20160405,150000
49982,2016-03-29 18:51:08,Skoda_Fabia_4_Tuerer_Bj:2004__85.000Tkm,1950,control,compact car,2004,manuell,0,fabia,7,benzin,skoda,NaN,2016-03-29 00:00:00,0,45884,20160329,90000
49985,2016-04-02 16:38:23,Verkaufe_meinen_vw_vento!,1000,control,NaN,1995,automatik,0,NaN,0,benzin,volkswagen,NaN,2016-04-02 00:00:00,0,30900,20160406,150000
49986,2016-04-04 20:46:02,Chrysler_300C_3.0_CRD_DPF_Automatik_Voll_Ausst...,15900,control,NaN,2010,automatik,218,300c,11,diesel,chrysler,no,2016-04-04 00:00:00,0,73527,20160406,125000
49987,2016-03-22 20:47:27,Audi_A3_Limousine_2.0_TDI_DPF_Ambition__NAVI__...,21990,control,NaN,2013,manuell,150,a3,11,diesel,audi,no,2016-03-22 00:00:00,0,94362,20160326,50000
49988,2016-03-28 19:49:51,BMW_330_Ci,9550,control,NaN,2001,manuell,231,3er,10,benzin,bmw,no,2016-03-28 00:00:00,0,83646,20160407,150000
49990,2016-03-21 19:54:19,Mercedes_Benz_A_200__BlueEFFICIENCY__Urban,17500,test,NaN,2012,manuell,156,a_klasse,12,benzin,mercedes_benz,no,2016-03-21 00:00:00,0,58239,20160406,30000
49992,2016-03-10 19:37:38,Fiat_Grande_Punto_1.4_T_Jet_16V_Sport,4800,control,compact car,2009,manuell,120,andere,9,lpg,fiat,no,2016-03-10 00:00:00,0,68642,20160313,125000
49993,2016-03-15 18:47:35,Audi_A3__1_8l__Silber;_schoenes_Fahrzeug,1650,control,compact car,1997,manuell,0,NaN,7,benzin,audi,NaN,2016-03-15 00:00:00,0,65203,20160406,150000
49994,2016-03-22 17:36:42,Audi_A6__S6__Avant_4.2_quattro_eventuell_Tausc...,5000,control,estate car,2001,automatik,299,a6,1,benzin,audi,no,2016-03-22 00:00:00,0,46537,20160406,150000
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,24900,control,NaN,2011,automatik,239,q5,1,diesel,audi,no,2016-03-27 00:00:00,0,82131,20160401,100000
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÃœV_neu+...,1980,control,cabriolet,1996,manuell,75,astra,5,benzin,opel,no,2016-03-28 00:00:00,0,44807,20160402,150000
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,13200,test,cabriolet,2014,automatik,69,500,11,benzin,fiat,no,2016-04-02 00:00:00,0,73430,20160404,5000
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,22900,control,estate car,2013,manuell,150,a3,11,diesel,audi,no,2016-03-08 00:00:00,0,35683,20160405,40000
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,1250,control,NaN,1996,manuell,101,vectra,1,benzin,opel,no,2016-03-13 00:00:00,0,45897,20160406,150000

In [59]:
autos['gearbox'].unique()

array(['manuell', 'automatik', nan], dtype=object)

In [60]:
gearbox_dict = {'manual':'manual','manuell': 'manual', 'automatik':'automatic'}
autos['gearbox'] = autos['gearbox'].map(gearbox_dict)
autos['gearbox']

0           manual
1        automatic
2           manual
3        automatic
4           manual
5        automatic
7           manual
12       automatic
13          manual
14          manual
15       automatic
17          manual
19          manual
20          manual
21          manual
22          manual
23          manual
24       automatic
28          manual
29       automatic
31       automatic
33          manual
34       automatic
35          manual
36          manual
37          manual
38          manual
39       automatic
40          manual
41          manual
           ...
49962       manual
49963       manual
49964    automatic
49965       manual
49966       manual
49967       manual
49968    automatic
49969       manual
49970    automatic
49972    automatic
49973       manual
49975    automatic
49976    automatic
49977       manual
49979       manual
49981       manual
49982       manual
49985    automatic
49986    automatic
49987       manual
49988       manual
49990       manual
49992       manual
49993       manual
49994    automatic
49995    automatic
49996       manual
49997    automatic
49998       manual
49999       manual
Name: gearbox, Length: 37211, dtype: object

In [63]:
top_brand_model = {}
for b in brands:
    sel_row = autos[autos['brand'] == b]
    top_models = selected_row['model']
    for m in top_models:
        top_brand_model[b] = top_models
print(top_brand_model)

{'mercedes_benz': 4          focus
35        mondeo
36        mondeo
54         focus
110       galaxy
121        focus
138        c_max
215        focus
220           ka
223       fiesta
243        focus
251       mondeo
257       mondeo
285        focus
307        focus
311        s_max
324          NaN
352        focus
358        focus
388       galaxy
406       fiesta
417       mondeo
476      transit
503       mondeo
514        focus
525      mustang
529        focus
556       galaxy
575       andere
596       galaxy
          ...
49251     fiesta
49269     mondeo
49296     fiesta
49300      focus
49312     fiesta
49317      focus
49341     fiesta
49361     andere
49375      focus
49402     galaxy
49412     mondeo
49430    mustang
49459     mondeo
49495      focus
49497     mondeo
49543      focus
49603    mustang
49608     fiesta
49656     mondeo
49664     mondeo
49718     fiesta
49759      focus
49765      focus
49767      focus
49804      c_max
49815    mustang
49837      focus
49871     fiesta
49922      focus
49953    mustang
Name: model, Length: 2185, dtype: object, 'bmw': 4          focus
35        mondeo
36        mondeo
54         focus
110       galaxy
121        focus
138        c_max
215        focus
220           ka
223       fiesta
243        focus
251       mondeo
257       mondeo
285        focus
307        focus
311        s_max
324          NaN
352        focus
358        focus
388       galaxy
406       fiesta
417       mondeo
476      transit
503       mondeo
514        focus
525      mustang
529        focus
556       galaxy
575       andere
596       galaxy
          ...
49251     fiesta
49269     mondeo
49296     fiesta
49300      focus
49312     fiesta
49317      focus
49341     fiesta
49361     andere
49375      focus
49402     galaxy
49412     mondeo
49430    mustang
49459     mondeo
49495      focus
49497     mondeo
49543      focus
49603    mustang
49608     fiesta
49656     mondeo
49664     mondeo
49718     fiesta
49759      focus
49765      focus
49767      focus
49804      c_max
49815    mustang
49837      focus
49871     fiesta
49922      focus
49953    mustang
Name: model, Length: 2185, dtype: object, 'ford': 4          focus
35        mondeo
36        mondeo
54         focus
110       galaxy
121        focus
138        c_max
215        focus
220           ka
223       fiesta
243        focus
251       mondeo
257       mondeo
285        focus
307        focus
311        s_max
324          NaN
352        focus
358        focus
388       galaxy
406       fiesta
417       mondeo
476      transit
503       mondeo
514        focus
525      mustang
529        focus
556       galaxy
575       andere
596       galaxy
          ...
49251     fiesta
49269     mondeo
49296     fiesta
49300      focus
49312     fiesta
49317      focus
49341     fiesta
49361     andere
49375      focus
49402     galaxy
49412     mondeo
49430    mustang
49459     mondeo
49495      focus
49497     mondeo
49543      focus
49603    mustang
49608     fiesta
49656     mondeo
49664     mondeo
49718     fiesta
49759      focus
49765      focus
49767      focus
49804      c_max
49815    mustang
49837      focus
49871     fiesta
49922      focus
49953    mustang
Name: model, Length: 2185, dtype: object, 'volkswagen': 4          focus
35        mondeo
36        mondeo
54         focus
110       galaxy
121        focus
138        c_max
215        focus
220           ka
223       fiesta
243        focus
251       mondeo
257       mondeo
285        focus
307        focus
311        s_max
324          NaN
352        focus
358        focus
388       galaxy
406       fiesta
417       mondeo
476      transit
503       mondeo
514        focus
525      mustang
529        focus
556       galaxy
575       andere
596       galaxy
          ...
49251     fiesta
49269     mondeo
49296     fiesta
49300      focus
49312     fiesta
49317      focus
49341     fiesta
49361     andere
49375      focus
49402     galaxy
49412     mondeo
49430    mustang
49459     mondeo
49495      focus
49497     mondeo
49543      focus
49603    mustang
49608     fiesta
49656     mondeo
49664     mondeo
49718     fiesta
49759      focus
49765      focus
49767      focus
49804      c_max
49815    mustang
49837      focus
49871     fiesta
49922      focus
49953    mustang
Name: model, Length: 2185, dtype: object, 'opel': 4          focus
35        mondeo
36        mondeo
54         focus
110       galaxy
121        focus
138        c_max
215        focus
220           ka
223       fiesta
243        focus
251       mondeo
257       mondeo
285        focus
307        focus
311        s_max
324          NaN
352        focus
358        focus
388       galaxy
406       fiesta
417       mondeo
476      transit
503       mondeo
514        focus
525      mustang
529        focus
556       galaxy
575       andere
596       galaxy
          ...
49251     fiesta
49269     mondeo
49296     fiesta
49300      focus
49312     fiesta
49317      focus
49341     fiesta
49361     andere
49375      focus
49402     galaxy
49412     mondeo
49430    mustang
49459     mondeo
49495      focus
49497     mondeo
49543      focus
49603    mustang
49608     fiesta
49656     mondeo
49664     mondeo
49718     fiesta
49759      focus
49765      focus
49767      focus
49804      c_max
49815    mustang
49837      focus
49871     fiesta
49922      focus
49953    mustang
Name: model, Length: 2185, dtype: object, 'audi': 4          focus
35        mondeo
36        mondeo
54         focus
110       galaxy
121        focus
138        c_max
215        focus
220           ka
223       fiesta
243        focus
251       mondeo
257       mondeo
285        focus
307        focus
311        s_max
324          NaN
352        focus
358        focus
388       galaxy
406       fiesta
417       mondeo
476      transit
503       mondeo
514        focus
525      mustang
529        focus
556       galaxy
575       andere
596       galaxy
          ...
49251     fiesta
49269     mondeo
49296     fiesta
49300      focus
49312     fiesta
49317      focus
49341     fiesta
49361     andere
49375      focus
49402     galaxy
49412     mondeo
49430    mustang
49459     mondeo
49495      focus
49497     mondeo
49543      focus
49603    mustang
49608     fiesta
49656     mondeo
49664     mondeo
49718     fiesta
49759      focus
49765      focus
49767      focus
49804      c_max
49815    mustang
49837      focus
49871     fiesta
49922      focus
49953    mustang
Name: model, Length: 2185, dtype: object}

In [61]:
autos['model'].value_counts()

golf                  2918
andere                2668
3er                   2285
passat                1152
a4                    1092
5er                   1065
c_klasse              1034
astra                  981
polo                   947
e_klasse               890
corsa                  826
a3                     768
a6                     753
transporter            646
focus                  583
fortwo                 514
1er                    511
2_reihe                504
a_klasse               443
touran                 433
fiesta                 429
zafira                 362
3_reihe                339
mondeo                 310
vectra                 305
clio                   303
x_reihe                296
twingo                 290
octavia                288
fabia                  272
                      ...
300c                    10
gl                      10
mii                     10
forester                 9
range_rover              9
ypsilon                  9
justy                    7
900                      7
exeo                     6
crossfire                6
amarok                   6
sirion                   6
lodgy                    5
range_rover_evoque       5
9000                     4
materia                  4
croma                    4
90                       4
nubira                   4
move                     4
delta                    3
v60                      3
kappa                    2
r19                      2
samara                   1
200                      1
b_max                    1
145                      1
rangerover               1
lanos                    1
Name: model, Length: 241, dtype: int64